unit Entities.TodoU;

interface


uses
  MVCFramework, MVCFramework.ActiveRecord, MVCFramework.Serializer.Commons,
  MVCFramework.SQLGenerators.Sqlite, MVCFramework.Nullables,
  MVCFramework.Validators;

type
  [MVCNameCase(ncLowerCase)]
  [MVCTable('todos')]
  TTodo = class(TMVCActiverecord)
  private
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    FID: NullableInt32;
    [MVCTableField('content')]
    [MVCRequired('content is required')]
    FContent: String;
  public
    property ID: NullableInt32 read FID write FID;
    property Content: String read FContent write FContent;
  end;

implementation

end.
