unit Entities.TodoU;

interface


uses
  MVCFramework, MVCFramework.ActiveRecord, MVCFramework.Serializer.Commons,
  MVCFramework.SQLGenerators.Sqlite, MVCFramework.Nullables;

type
  [MVCNameCase(ncLowerCase)]
  [MVCTable('todos')]
  TTodo = class(TMVCActiverecord)
  private
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    FID: NullableInt32;
    [MVCTableField('content')]
    FContent: String;
    procedure SetID(const Value: NullableInt32);
    procedure SetContent(const Value: String);
  public
    property ID: NullableInt32 read FID write SetID;
    property Content: String read FContent write SetContent;
  end;

implementation

{ TTodo }

procedure TTodo.SetContent(const Value: String);
begin
  FContent := Value;
end;

procedure TTodo.SetID(const Value: NullableInt32);
begin
  FID := Value;
end;

end.
